# Generated by Django 5.2.9 on 2026-05-02 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('invoice_template', models.CharField(default='standard', max_length=50)),
                ('receipt_template', models.CharField(default='thermal', max_length=50)),
                ('loyalty_points_per_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='settings_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_closings', to='settings_app.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('document_type', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_sequences', to='settings_app.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'year', 'document_type'), name='unique_branch_year_doctype')],
            },
        ),
    ]
