# Generated by Django 5.2.9 on 2026-05-06 08:35

from django.db import migrations, models


def link_existing_parties_to_all_active_branches(apps, schema_editor):
    Branch = apps.get_model("settings_app", "Branch")
    Supplier = apps.get_model("suppliers", "Supplier")
    bids = list(Branch.objects.filter(is_active=True).values_list("id", flat=True))
    if not bids:
        return
    for s in Supplier.objects.all():
        s.branches.set(bids)


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_module2_branch_fields'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='settings_app.branch'),
        ),
        migrations.RunPython(link_existing_parties_to_all_active_branches, migrations.RunPython.noop),
    ]
