# Generated by Django 5.2.9 on 2026-05-02 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('cash', 'Cash'), ('bank', 'Bank'), ('expense', 'Expense'), ('sales', 'Sales'), ('purchase', 'Purchase')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('entry_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
