# Generated by Django 5.2.9 on 2026-05-06 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Permission = apps.get_model("accounts", "Permission")
    UserBranchAccess = apps.get_model("accounts", "UserBranchAccess")
    User.objects.filter(role="admin").update(role="super_admin")
    User.objects.filter(role="inventory_staff").update(role="inventory_manager")
    Permission.objects.filter(role="admin").update(role="super_admin")
    Permission.objects.filter(role="inventory_staff").update(role="inventory_manager")

    for u in User.objects.exclude(branch_id=None).iterator(chunk_size=200):
        UserBranchAccess.objects.get_or_create(user_id=u.id, branch_id=u.branch_id)

    for new_role, tmpl in (("owner", "manager"), ("sales_staff", "cashier")):
        for p in Permission.objects.filter(role=tmpl).iterator():
            if Permission.objects.filter(role=new_role, module=p.module).exists():
                continue
            Permission.objects.create(
                role=new_role,
                module=p.module,
                can_create=p.can_create,
                can_edit=p.can_edit,
                can_delete=p.can_delete,
                can_print=p.can_print,
                can_refund=p.can_refund,
                can_view_reports=p.can_view_reports,
            )


def backwards(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    User = apps.get_model("accounts", "User")
    Permission.objects.filter(role__in=["owner", "sales_staff"]).delete()
    User.objects.filter(role="super_admin").update(role="admin")
    User.objects.filter(role="inventory_manager").update(role="inventory_staff")
    Permission.objects.filter(role="super_admin").update(role="admin")
    Permission.objects.filter(role="inventory_manager").update(role="inventory_staff")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('settings_app', '0002_branch_name_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'id']},
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('inventory_manager', 'Inventory Manager'), ('accountant', 'Accountant'), ('sales_staff', 'Sales Staff')], default='cashier', max_length=32),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBranchAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='settings_app.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='accounts_userbranchaccess_unique')],
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
