# Generated by Django 5.2.9 on 2026-05-06 08:35

from django.db import migrations, models


def link_existing_customers_to_all_active_branches(apps, schema_editor):
    Branch = apps.get_model("settings_app", "Branch")
    Customer = apps.get_model("customers", "Customer")
    bids = list(Branch.objects.filter(is_active=True).values_list("id", flat=True))
    if not bids:
        return
    for c in Customer.objects.all():
        c.branches.set(bids)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('settings_app', '0003_module2_branch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='customers', to='settings_app.branch'),
        ),
        migrations.RunPython(link_existing_customers_to_all_active_branches, migrations.RunPython.noop),
    ]
